### ISSUE TITLE
--create is broken

### ISSUE THREAD

**Issue by nicoboss** [nicoboss/nsz#118]
--create is broken as reported in #113 by @blacklein

python .\nsz.py --create out.nsp .\in\test.ncz

```
Creating "a"
        Repacking to NSP...
nut exception: 'Counter' object has no attribute 'write'
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\nsz\nsz.py", line 18, in <module>
    nsz.main()
  File "C:\Users\Administrator\Documents\GitHub\nsz\nsz\__init__.py", line 148, in main
    nsp.pack(args.file)
  File "C:\Users\Administrator\Documents\GitHub\nsz\nsz\Fs\Nsp.py", line 384, in pack
    t.write('\t\tWriting header...')
AttributeError: 'Counter' object has no attribute 'write'
```
